# Generated by Django 2.2.17 on 2021-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='new_field_with_a_very_long_name',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
